//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONE._07DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T002验证码表> T002验证码表 { get; set; }
        public virtual DbSet<T003关注表> T003关注表 { get; set; }
        public virtual DbSet<T010博文表> T010博文表 { get; set; }
        public virtual DbSet<T011点赞表> T011点赞表 { get; set; }
        public virtual DbSet<T012评论表> T012评论表 { get; set; }
        public virtual DbSet<T013评论回复表> T013评论回复表 { get; set; }
        public virtual DbSet<T001用户表> T001用户表 { get; set; }
    }
}
