//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONE._07DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T001用户表
    {
        public T001用户表()
        {
            this.T003关注表 = new HashSet<T003关注表>();
            this.T003关注表1 = new HashSet<T003关注表>();
            this.T010博文表 = new HashSet<T010博文表>();
            this.T011点赞表 = new HashSet<T011点赞表>();
            this.T012评论表 = new HashSet<T012评论表>();
        }
    
        public string 注册邮箱 { get; set; }
        public string 用户名 { get; set; }
        public string 密码 { get; set; }
        public string 个性标签 { get; set; }
        public bool 是否封锁 { get; set; }
        public int 粉丝数 { get; set; }
        public int 关注数 { get; set; }
        public string 角色 { get; set; }
        public string 头像 { get; set; }
    
        public virtual ICollection<T003关注表> T003关注表 { get; set; }
        public virtual ICollection<T003关注表> T003关注表1 { get; set; }
        public virtual ICollection<T010博文表> T010博文表 { get; set; }
        public virtual ICollection<T011点赞表> T011点赞表 { get; set; }
        public virtual ICollection<T012评论表> T012评论表 { get; set; }
    }
}
