//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONE._07DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T010博文表
    {
        public T010博文表()
        {
            this.T011点赞表 = new HashSet<T011点赞表>();
            this.T012评论表 = new HashSet<T012评论表>();
        }
    
        public int T010_id { get; set; }
        public string 标题 { get; set; }
        public string 正文 { get; set; }
        public string 图片链接 { get; set; }
        public string 音乐链接 { get; set; }
        public string 博主邮箱 { get; set; }
        public string 标签 { get; set; }
        public int 点赞数 { get; set; }
        public bool 是否封锁 { get; set; }
        public bool 是否公开 { get; set; }
        public Nullable<System.DateTime> 发布时间 { get; set; }
    
        public virtual ICollection<T011点赞表> T011点赞表 { get; set; }
        public virtual ICollection<T012评论表> T012评论表 { get; set; }
        public virtual T001用户表 T001用户表 { get; set; }
    }
}
