//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONE._07DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T011点赞表
    {
        public int T011_id { get; set; }
        public string 来自用户 { get; set; }
        public int 博文id { get; set; }
    
        public virtual T010博文表 T010博文表 { get; set; }
        public virtual T001用户表 T001用户表 { get; set; }
    }
}
