//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONE._07DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T012评论表
    {
        public T012评论表()
        {
            this.T013评论回复表 = new HashSet<T013评论回复表>();
        }
    
        public int T012_id { get; set; }
        public string 评论用户id { get; set; }
        public int 博文id { get; set; }
        public string 评论内容 { get; set; }
        public Nullable<System.DateTime> 评论时间 { get; set; }
    
        public virtual T010博文表 T010博文表 { get; set; }
        public virtual ICollection<T013评论回复表> T013评论回复表 { get; set; }
        public virtual T001用户表 T001用户表 { get; set; }
    }
}
