//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONE._07DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T013评论回复表
    {
        public int T013_replyId { get; set; }
        public int 评论ID { get; set; }
        public string 回复内容 { get; set; }
        public string 评论人ID { get; set; }
        public string 回复至ID { get; set; }
        public Nullable<System.DateTime> 回复时间 { get; set; }
    
        public virtual T012评论表 T012评论表 { get; set; }
    }
}
